version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_NAME=fastfood
  db:
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=fastfood
